use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Livepeer Valuation API",
        version = "1.9",
        description = "HTTP API for indexed Livepeer protocol events, valuation outcomes, token prices, stake snapshots, governance views, and transcoder context. The API is backed by deterministic replayable Postgres state derived from Arbitrum and Ethereum RPC inputs."
    ),
    paths(
        crate::routes::operational::health,
        crate::routes::operational::metrics,
        crate::routes::operational::backfill_status,
        crate::routes::events::list,
        crate::routes::events::get_one,
        crate::routes::valuations::for_event,
        crate::routes::valuations::list,
        crate::routes::aggregations::events,
        crate::routes::payouts::leaderboard,
        crate::routes::payouts::summary_daily,
        crate::routes::payouts::summary_weekly,
        crate::routes::payouts::summary_monthly,
        crate::routes::rewards::leaderboard,
        crate::routes::rewards::summary_daily,
        crate::routes::rewards::summary_weekly,
        crate::routes::rewards::summary_monthly,
        crate::routes::tickets::timeseries_daily,
        crate::routes::reports::payouts_csv,
        crate::routes::reports::rewards_csv,
        crate::routes::reports::gateway_payouts_csv,
        crate::routes::reports::orchestrator_tickets_latest,
        crate::routes::reports::gateway_tickets,
        crate::routes::governance::list,
        crate::routes::governance::get_one,
        crate::routes::governance::votes,
        crate::routes::prices::at_block,
        crate::routes::prices::latest,
        crate::routes::prices::range,
        crate::routes::profiles::orchestrators_list,
        crate::routes::profiles::orchestrators_get,
        crate::routes::profiles::gateways_list,
        crate::routes::profiles::gateways_get,
        crate::routes::gateways::balance_latest,
        crate::routes::gateways::balance_at_block,
        crate::routes::gateways::balance_history,
        crate::routes::gateways::claimants_at_block,
        crate::routes::gateways::claimants_history,
        crate::routes::gateways::flows,
        crate::routes::gateways::payouts,
        crate::routes::gateways::recipients,
        crate::routes::gateways::summary,
        crate::routes::gateways::analytics_summary,
        crate::routes::stake::at_block,
        crate::routes::stake::range,
        crate::routes::stake::delegators_at_block,
        crate::routes::transcoders::latest,
        crate::routes::transcoders::at_block,
        crate::routes::transcoders::history,
        crate::routes::transcoders::lifecycle_latest,
        crate::routes::transcoders::lifecycle_at_block,
        crate::routes::transcoders::lifecycle_history,
        crate::routes::transcoders::profile_at_block,
        // TD-027 — orchestrator history, delegators, network stats
        crate::routes::profiles::orchestrators_stake_history,
        crate::routes::profiles::orchestrators_cuts_history,
        crate::routes::profiles::orchestrators_net_economics,
        crate::routes::delegators::get,
        crate::routes::delegators::list,
        crate::routes::delegators::events_for,
        crate::routes::delegators::for_orchestrator,
        crate::routes::network::stats,
        crate::routes::network::round_get
    ),
    components(
        schemas(
            crate::error::ErrorEnvelope,
            crate::error::ErrorBody,
            crate::routes::operational::BackfillStatus,
            crate::routes::operational::Checkpoint,
            crate::routes::events::EventsQuery,
            crate::routes::events::EventRow,
            crate::routes::events::ValuationInline,
            crate::routes::events::EventListResponse,
            crate::routes::valuations::ValuationsQuery,
            crate::routes::valuations::ValuationRow,
            crate::routes::valuations::ValuationListResponse,
            crate::routes::aggregations::AggregationsQuery,
            crate::routes::aggregations::AggregationsResponse,
            crate::routes::aggregations::BucketRow,
            crate::routes::payouts::PayoutLeaderboardQuery,
            crate::routes::payouts::PayoutSummaryQuery,
            crate::routes::payouts::PayoutLeaderboardRow,
            crate::routes::payouts::PayoutLeaderboardMeta,
            crate::routes::payouts::PayoutLeaderboardResponse,
            crate::routes::payouts::PayoutSummaryResponse,
            crate::routes::rewards::RewardLeaderboardQuery,
            crate::routes::rewards::RewardSummaryQuery,
            crate::routes::rewards::RewardLeaderboardRow,
            crate::routes::rewards::RewardLeaderboardMeta,
            crate::routes::rewards::RewardLeaderboardResponse,
            crate::routes::rewards::RewardSummaryResponse,
            crate::routes::tickets::TicketsTimeseriesQuery,
            crate::routes::tickets::TicketSeriesRow,
            crate::routes::tickets::TicketsTimeseriesResponse,
            crate::routes::reports::ReportQuery,
            crate::routes::reports::TicketHistoryQuery,
            crate::routes::reports::TicketHistoryRow,
            crate::routes::reports::TicketHistoryResponse,
            crate::routes::governance::ProposalsQuery,
            crate::routes::governance::ProposalRow,
            crate::routes::governance::VoteTally,
            crate::routes::governance::ProposalListResponse,
            crate::routes::governance::VotesQuery,
            crate::routes::governance::VoteRow,
            crate::routes::governance::VotesCoverage,
            crate::routes::governance::VoteListResponse,
            crate::routes::prices::PriceRow,
            crate::routes::prices::RangeQuery,
            crate::routes::prices::RangeResponse,
            crate::routes::profiles::OrchestratorsQuery,
            crate::routes::profiles::GatewaysQuery,
            crate::routes::profiles::OrchestratorProfileRow,
            crate::routes::profiles::GatewayProfileRow,
            crate::routes::profiles::ProfileListMeta,
            crate::routes::profiles::OrchestratorListResponse,
            crate::routes::profiles::GatewayListResponse,
            crate::routes::gateways::GatewayBalanceRow,
            crate::routes::gateways::GatewayBalanceHistoryQuery,
            crate::routes::gateways::GatewayBalanceHistoryResponse,
            crate::routes::gateways::GatewayClaimantsQuery,
            crate::routes::gateways::GatewayClaimantRow,
            crate::routes::gateways::GatewayClaimantsResponse,
            crate::routes::gateways::GatewayPayoutSemantics,
            crate::routes::gateways::GatewayFlowsQuery,
            crate::routes::gateways::GatewayFlowRow,
            crate::routes::gateways::GatewayFlowsResponse,
            crate::routes::gateways::GatewayPayoutsQuery,
            crate::routes::gateways::GatewayRecipientsQuery,
            crate::routes::gateways::GatewayRecipientRow,
            crate::routes::gateways::GatewayRecipientsResponse,
            crate::routes::gateways::GatewaySummaryQuery,
            crate::routes::gateways::GatewaySummaryRow,
            crate::routes::gateways::GatewayAnalyticsBucket,
            crate::routes::gateways::GatewaySummaryResponse,
            crate::routes::gateways::GatewayAnalyticsSummaryResponse,
            crate::routes::stake::StakeRow,
            crate::routes::stake::StakeRangeQuery,
            crate::routes::stake::StakeRangeResponse,
            crate::routes::stake::DelegatorStakeRow,
            crate::routes::stake::DelegatorListResponse,
            crate::routes::transcoders::HistoryQuery,
            crate::routes::transcoders::TranscoderParamsRow,
            crate::routes::transcoders::TranscoderParamsHistoryResponse,
            crate::routes::transcoders::TranscoderLifecycleRow,
            crate::routes::transcoders::TranscoderLifecycleHistoryResponse,
            crate::routes::transcoders::TranscoderProfileResponse,
            // TD-027 — orchestrator history, delegators, network stats
            crate::routes::profiles::StakeHistoryQuery,
            crate::routes::profiles::StakeHistoryPoint,
            crate::routes::profiles::StakeHistoryResponse,
            crate::routes::profiles::CutsHistoryPoint,
            crate::routes::profiles::CutsHistoryResponse,
            crate::routes::profiles::NetEconomicsQuery,
            crate::routes::profiles::NetEconomicsResponse,
            crate::routes::delegators::DelegationRow,
            crate::routes::delegators::DelegatorResponse,
            crate::routes::delegators::OrchDelegatorRow,
            crate::routes::delegators::OrchDelegatorsMeta,
            crate::routes::delegators::OrchDelegatorsResponse,
            crate::routes::delegators::OrchDelegatorsQuery,
            crate::routes::delegators::DelegatorIndexRow,
            crate::routes::delegators::DelegatorIndexMeta,
            crate::routes::delegators::DelegatorIndexResponse,
            crate::routes::delegators::DelegatorIndexQuery,
            crate::routes::delegators::DelegatorEventRow,
            crate::routes::delegators::DelegatorEventsMeta,
            crate::routes::delegators::DelegatorEventsResponse,
            crate::routes::delegators::DelegatorEventsQuery,
            crate::routes::network::NetworkStatsResponse,
            crate::routes::network::RoundOrchSummary,
            crate::routes::network::RoundSummaryResponse
        )
    ),
    tags(
        (name = "Operational", description = "Health, metrics, and pipeline checkpoint visibility."),
        (name = "Events", description = "Canonical raw protocol events with optional inline valuation outcomes."),
        (name = "Valuations", description = "Versioned valuation outcomes attached to finalized monetary events."),
        (name = "Aggregations", description = "Time-bucketed analytics over raw events and valuation rows."),
        (name = "Payouts", description = "Materialized payout leaderboards and period summaries derived from WinningTicketRedeemed rows."),
        (name = "Reports", description = "Direct-query CSV exports and ticket history views over canonical event rows."),
        (name = "Rewards", description = "Materialized reward leaderboards and period summaries derived from Reward rows."),
        (name = "Tickets", description = "Daily WinningTicketRedeemed timeseries split by broadcaster kind."),
        (name = "Governance", description = "Governor proposal lifecycle and vote tally convenience views."),
        (name = "Prices", description = "Cached on-chain token prices keyed by asset, quote, and block."),
        (name = "Profiles", description = "Entity-centric orchestrator and gateway profile views built from deterministic materialized state plus optional overlays."),
        (name = "Gateways", description = "TicketBroker sender balances, payout flows, and rolling gateway summaries."),
        (name = "Stake", description = "Delegator stake snapshots and bounded stake history derived from protocol events and exact reconciliation."),
        (name = "Transcoders", description = "Transcoder parameter history, lifecycle state, and delegator set snapshots."),
        (name = "Orchestrator history", description = "Per-round stake history, cut-change timeline, and net-economics windows for a single orchestrator (TD-027)."),
        (name = "Delegators", description = "Per-delegator portfolio views derived from stake_balances_by_block + delegator_registry (TD-027)."),
        (name = "Network", description = "Network-level summaries: dashboard stats and per-round detail (TD-027).")
    )
)]
pub struct ApiDoc;
