[package]
name = "livepeer-orchestrator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "livepeer-orchestrator"
path = "src/main.rs"

[dependencies]
livepeer-core.workspace = true
anyhow.workspace = true
bigdecimal.workspace = true
clap.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sqlx.workspace = true
serde_json.workspace = true
livepeer-indexer = { path = "../livepeer-indexer" }
livepeer-finality-watcher = { path = "../livepeer-finality-watcher" }
livepeer-valuator = { path = "../livepeer-valuator" }
livepeer-staker = { path = "../livepeer-staker" }
livepeer-rollups = { path = "../livepeer-rollups" }
livepeer-seed-migrator = { path = "../livepeer-seed-migrator" }
